
- name: Install Apache, a web server
  hosts: all
  tasks:
    - name: Ensure the tomcat software is installed
      yum:
        name: httpd
        state: present
    - name: Ensure the httpd service is enabled and started
      service:
        name: httpd
        enabled: yes
        state: started
    - name: Check so that web server is alive
      uri:
        url: http://localhost
