- name: Install Tomcat, a java application server
  hosts: all
  tasks:
    - name: Ensure the tomcat software is installed
      yum:
        name: tomcat
        state: present
    - name: Ensure the tomcat service is enabled and started
      service:
        name: tomcat
        enabled: yes
        state: started
      
